local u = require("utils")

u.nnoremap("<leader>e", ":Ex<CR>", {})
u.nnoremap("<leader>a", require("harpoon.mark").add_file, {})
u.nnoremap("<leader>bn", ":lua print(vim.fn.bufname())<CR>", {})
-- u.nnoremap("<leader>pp", ":lua print(package.path)<CR>", {})
u.nnoremap("<C-e>", ":lua require('harpoon.ui').toggle_quick_menu()<CR>", {})
u.nnoremap("<C-h>", ":lua require('harpoon.ui').nav_file(1)<CR>", {})
u.nnoremap("<C-t>", ":lua require('harpoon.ui').nav_file(2)<CR>", {})
u.nnoremap("<C-n>", ":lua require('harpoon.ui').nav_file(3)<CR>", {})
u.nnoremap("<C-s>", ":lua require('harpoon.ui').nav_file(4)<CR>", {})
u.nnoremap("<C-f>", ':lua require("harpoon.term").sendCommand(1, "tmux-sessionizer\\n"); require("harpoon.term").gotoTerminal(1)<CR>', {})
u.tnoremap("<Esc>", "<C-\\><C-n>")
u.nnoremap("<leader>y", '"+y', {})
u.vnoremap("<leader>y", '"+y', {})
u.nnoremap("<leader>d", '"_d', {})
u.vnoremap("<leader>d", '"_d', {})
u.nnoremap("<leader>p", '"+p', {})
u.vnoremap("<leader>p", '"+p', {})
u.nnoremap("<leader>/", "<ESC><CMD>lua require('Comment.api').toggle_current_linewise()<CR>", {})
u.vnoremap("<leader>/", "<ESC><CMD>lua require('Comment.api').toggle_linewise_op(vim.fn.visualmode())<CR>", {})
