local Remap = require("numine.mapper")
local nnoremap = Remap.nnoremap

nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>st", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
nnoremap("<C-p>", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<Leader>sf", function()
    require('telescope.builtin').find_files()
end)

nnoremap("<leader>sw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>sb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>sh", function()
    require('telescope.builtin').help_tags()
end)

nnoremap("<leader>src", function()
    require('numine.telescope').search_dotfiles({ hidden = true })
end)
nnoremap("<leader>sa", function()
    require('numine.telescope').anime_selector()
end)
nnoremap("<leader>sg", function()
    require('numine.telescope').git_branches()
end)
-- nnoremap("<leader>gw", function()
--     require('telescope').extensions.git_worktree.git_worktrees()
-- end)
-- nnoremap("<leader>gm", function()
--     require('telescope').extensions.git_worktree.create_git_worktree()
-- end)
nnoremap("<leader>td", function()
    require('numine.telescope').dev()
end)
